openapi: 3.0.0
info:
  title: Slack Application
  description: App that mimics Slack
  version: '0.1'
servers: 
  - url: http://localhost:3000/api/
    description: local dev
  - url: https://passport-mocha-12112018.herokuapp.com/api/
    description: heroku app
tags: 
  - name: Workspaces
components:
  securitySchemes:
    bearerAuth:       
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /workspaces:
    post:
      tags:
        - Workspaces
      summary: create a new workspace
      requestBody:
        content: 
          application/json:
            schema:
              $ref: "/db.json"
            example:
              id: 12345
              name: "board1"
              users: []
              channels: []
      responses:
        '200':
          description: OK
    get:
      tags:
        - Workspaces
      summary: Finds all Workspaces
      security:
        - bearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                 $ref: "/db.json"
              example:
                  id: 12345
                  name: "board1"
                  users: []
                  channels: []
              
  /workspaces/{id}:
    get:
      tags:
        - Workspaces
      summary: Find Workspace by ID
      description: Returns a single workspace
      parameters:
        - name: id
          in: path
          description: ID of workspace to return
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      responses:
        '200':
          description: successful operation
        '404':
          description: Workspace not found
    
    delete:
      tags:
        - Workspaces
      summary: Deletes a workspace
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      responses:
        '200':
          description: OK
        '404':
          description: Workspace not found
      
    put:
      tags:
        - Workspaces
      summary: Updated board
      description: This can only be done by the logged in user.
      parameters:
        - name: id
          in: path
          description: id that need to be updated
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      requestBody:
        content: 
          application/json:
            schema:
              $ref: "/db.json"
            example:
              id: 12345
              name: "board1"
              users: []
              channels: []
      responses:
        '201':
          description: OK
        '404':
          description: board not found
          
  /workspaces/{id}/users:
    put:
      tags:
        - Workspaces
      summary: create a new user in the workspace
      description: ''
      parameters:
        - name: id
          in: path
          description: workspace id where the user is created
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      requestBody:
        content: 
          application/json:
            schema:
              $ref: "/db.json"
            example:
              name: "user1"
      responses:
        '200':
          description: OK
        '405':
          description: Invalid workspace id
  
  /workspaces/{id}/channels:
    put:
      tags:
        - Workspaces
      summary: create a new channel in the workspace
      description: ''
      parameters:
        - name: id
          in: path
          description: workspace id where the channel is created
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      requestBody:
        content: 
          application/json:
            schema:
              $ref: "/db.json"
            example:
              name: "channel1"
      responses:
        '200':
          description: OK
        '405':
          description: Invalid workspace id
          
    get:
      tags:
        - Workspaces
      summary: Find channels by workspace ID
      description: Returns channels of a  single workspace
      parameters:
        - name: id
          in: path
          description: ID of workspace to return
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      responses:
        '200':
          description: successful operation
        '404':
          description: Channels not found
          
  /channels/:id:
    get:
      tags:
        - Channels
      summary: Find a channel by channel ID
      description: Returns channel of a particular ID
      parameters:
        - name: id
          in: path
          description: ID of workspace to return
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      responses:
        '200':
          description: successful operation
        '404':
          description: channel not found
  
  /channels/:id/messages:
    put:
      tags:
        - Channels
      summary: update the channel in the workspace
      description: ''
      parameters:
        - name: id
          in: path
          description: channel id
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      requestBody:
        content: 
          application/json:
            schema:
              $ref: "/db.json"
            example:
              message: "hi"
      responses:
        '200':
          description: OK
        '405':
          description: Invalid channel id
          
  /channels/:id/users:
    put:
      tags:
        - Channels
      summary: update the channel in the workspace
      description: ''
      parameters:
        - name: id
          in: path
          description: channel id
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      requestBody:
        content: 
          application/json:
            schema:
              $ref: "/db.json"
            example:
              user: "user1"
      responses:
        '200':
          description: OK
        '405':
          description: Invalid channel id
          
          
    
      
  
      
      